##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# This playbook is a subsequent playbook
##########################################################################################
# DO NOT RUN THIS IF YOU HAVE NOT RUN deploy-network.yaml and deployed the Fabric network
##########################################################################################
# This playbook can only be run after all pods and orderers are available
# Please use the same network.yaml to run this playbook as used for deploy-network.yaml
---
  # This will apply to ansible_provisioners. /etc/ansible/hosts should be configured with this group
- hosts: ansible_provisioners
  gather_facts: no
  no_log: "{{ no_ansible_log | default(false) }}"
  tasks:
    # Step 1: Create channel using OSN admin API (Fabric 2.3+)
    - name: Create channel using OSN admin
      include_role:
        name: "create/osnchannels"
      vars:
        build_path: "./build"
        docker_url: "{{ network.docker.url }}"
      loop: "{{ network['channels'] }}"
      when: item.channel_status == 'new'

    # Step 2: Join peers to the channel
    - name: Join peers to channel
      include_role:
        name: "create/channels_join"
      vars:
        build_path: "./build"
        docker_url: "{{ network.docker.url }}"
        participants: "{{ item.participants }}"
      loop: "{{ network['channels'] }}"
      when: item.channel_status == 'new'

    # delete build directory
    - name: Remove build directory
      file:
        path: "./build"
        state: absent
  vars: #These variables can be overriden from the command line
    privilege_escalate: false           #Default to NOT escalate to root privledges
    install_os: "linux"                 #Default to linux OS
    install_arch:  "amd64"              #Default to amd64 architecture
    bin_install_dir:  "~/bin"            #Default to /bin install directory for binaries
